# pull official base image
FROM node:15.1.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
# ENV PATH=$PATH:/home/node/.npm-global/bin 

# install app dependencies
COPY ["package.json", "./"]
RUN apk add --no-cache python make g++
RUN npm install
RUN npm install @vue/cli -g --legacy-peer-deps
RUN npm i node-sass@5.0.0
RUN npm i vue-template-compiler
RUN npm i sass-loader@10.1.1 --force

# add app
COPY . ./

# start app
# CMD ["npm", "run", "serve"]

USER node
